authors: [eccentric_nz, ewized]
description: A plugin for all Doctor Who fans - create and use a TARDIS! Teleport to random destinations - it's bigger on the inside!
main: me.eccentric_nz.TARDIS.TARDIS
name: TARDIS
startup: postworld
softdepend: [Multiverse-Core,MultiWorld,My Worlds,WorldGuard,WorldBorder,Towny]
website: http://dev.bukkit.org/server-mods/TARDIS/
dev-url: http://dev.bukkit.org/server-mods/TARDIS/
url: http://eccentricdevotion.github.io/TARDIS/
version: '2.3-pre'
permissions:
  tardis.admin:
    description: Allow players access to the TARDIS admin commands.
    default: op
  tardis.delete:
    description: Allow players to delete any TARDIS.
    default: false
  tardis.skeletonkey:
    description: Allow players to enter any TARDIS.
    default: false
  tardis.use:
    description: Allow players to create & delete a TARDIS, and teleport to destinations.
    children:
      tardis.create: true
      tardis.exterminate: true
      tardis.timetravel: true
      tardis.list: true
      tardis.save: true
      tardis.enter: true
      tardis.find: true
      tardis.add: true
      tardis.help: true
      tardis.update: true
      tardis.rebuild: true
      tardis.book: true
    default: op
  tardis.exile:
    description: Disallow players from travelling anywhere but to areas they have a permission node for.
    default: false
  tardis.create:
    description: Allow players to create a TARDIS.
    default: op
  tardis.exterminate:
    description: Allow players to delete their own TARDIS.
    default: op
  tardis.timetravel:
    description: Allow players to teleport to random locations and saved destinations.
    default: op
  tardis.timetravel.player:
    description: Allow players to teleport to player locations.
    default: op
  tardis.timetravel.location:
    description: Allow players to teleport to coordinates.
    default: op
  tardis.list:
    description: Allow players to list saved time travel destinations.
    default: op
  tardis.save:
    description: Allow players to save time travel destinations.
    default: op
  tardis.home:
    description: Allow players to save a time travel destination as their home.
    default: op
  tardis.enter:
    description: Allow players to enter a TARDIS.
    default: op
  tardis.find:
    description: Allow players to find their TARDIS.
    default: op
  tardis.add:
    description: Allow players to add/remove companions to their TARDIS.
    default: op
  tardis.help:
    description: Allow players to view TARDIS help pages.
    default: true
  tardis.update:
    description: Allow players to modify the TARDIS interior.
    default: true
  tardis.rebuild:
    description: Allow players to rebuild the TARDIS.
    default: true
  tardis.bigger:
    description: Allow players to build the 'bigger' TARDIS.
    default: op
  tardis.deluxe:
    description: Allow players to build the 'deluxe' TARDIS.
    default: op
  tardis.eleventh:
    description: Allow players to build the 'eleventh' TARDIS.
    default: op
  tardis.redstone:
    description: Allow players to build the 'redstone' TARDIS.
    default: op
  tardis.end:
    description: Allow players to time travel to the END.
    default: op
  tardis.nether:
    description: Allow players to time travel to the NETHER.
    default: op
  tardis.room:
    description: Allow players to grow extra rooms.
    children:
      tardis.room.antigravity: true
      tardis.room.arboretum: true
      tardis.room.baker: true
      tardis.room.bedroom: true
      tardis.room.cross: true
      tardis.room.empty: true
      tardis.room.farm: true
      tardis.room.gravity: true
      tardis.room.greenhouse: true
      tardis.room.harmony: true
      tardis.room.kitchen: true
      tardis.room.library: true
      tardis.room.long: true
      tardis.room.mushroom: true
      tardis.room.passage: true
      tardis.room.pool: true
      tardis.room.vault: true
      tardis.room.wood: true
      tardis.room.workshop: true
    default: op
  tardis.farm:
    description: Allow players to farm mobs.
    default: op
  tardis.autonomous:
    description: Allow players to use the TARDIS autonomous homing function.
    default: op
  tardis.book:
    description: Allow players to use TARDIS books and gain achievements.
    default: op
  tardis.backdoor:
    description: Allow players to add a TARDIS back door.
    default: op
  tardis.prune.bypass:
    description: Ignore /tardisadmin prune [days] command to remove unused TARDISes.
    default: op
commands:
  tardis:
    aliases: [tt,ttardis,/tardis,timelord]
    description: Manipulate TARDISs (TARDII?) with various arguments (list, save, find, help, etc). Type /TARDIS help - to see more.
    chameleon:
      description: Toggle the TARDIS Chameleon Circuit on and off.
      usage: /<command> chameleon [on|off|short|reset]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    list:
      description: List saved time travel locations.
      usage: /<command> list
      permission: tardis.list
      permission-message: You don't have the permission <permission> to use this command
    save:
      description: Save the current location of the TARDIS Police Box.
      usage: /<command> save [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    setdest:
      description: Save a destination determined by the block you are looking at.
      usage: /<command> setdest [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    removesave:
      description: Delete a saved destination.
      usage: /<command> removesave [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    home:
      description: Save a time travel location as home.
      usage: /<command> home
      permission: tardis.home
      permission-message: You don't have the permission <permission> to use this command
    find:
      description: Shows you the location of your TARDIS.
      usage: /<command> find
      permission: tardis.find
      permission-message: You don't have the permission <permission> to use this command
    add:
      description: Add a companion that can travel with you in your TARDIS.
      usage: /<command> add [player name]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a companion from your TARDIS.
      usage: /<command> remove [player name]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    update:
      description: Modify the interior of the TARDIS.
      usage: /<command> update [door|button|save-repeater|x-repeater|z-repeater|y-repeater]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    rebuild:
      description: Rebuild the TARDIS.
      usage: /<command> rebuild
      permission: tardis.rebuild
      permission-message: You don't have the permission <permission> to use this command
    namekey:
      description: Rename the TARDIS key Item.
      usage: Hold the key in your hand, then type /<command> namekey [new name]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    reload:
      description: Reloads the TARDIS configuration.
      usage: /<command> reload
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    help:
      description: View TARDIS help pages.
      usage: /<command> help [command]
  tardistravel:
    aliases: ttravel
    description: Travel to destinations in various ways.
    usage: |
      /<command> [player] or /<command> [world x y z] or /<command> dest [name] or /<command> area [name]
      Example: /<command> eccentric_nz - travel to a players location
      Example: /<command> New_new_earth -117 64 273 - travel to co-ordinates in a specific world
      Example: /<command> dest mine - travel to saved destination called 'mine'
      Example: /<command> area airport - travel to the TARDIS area called 'airport'
    permission: tardis.timetravel
    permission-message: You don't have the permission <permission> to use this command
  tardisadmin:
    aliases: tadmin
    description: Set TARDIS configuration options.
    usage: /<command> [config option] [value]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
  tardisroom:
    aliases: troom
    description: Set TARDIS room configuration options, and add new rooms.
    usage: /<command> add [name] or /<command> [name] [boolean|integer|string] or /<command> blocks [name|save]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
  tardisprefs:
    aliases: tprefs
    description: Set player preferences.
    usage: /<command> [preference] [on|off]
    sfx:
      description: Toggle the TARDIS sound effects on and off.
      usage: /<command> sfx [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    quotes:
      description: Toggle the TARDIS quotes on and off.
      usage: /<command> quotes [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    platform:
      description: Toggle the TARDIS platform on and off.
      usage: /<command> platform [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    key:
      description: Set the TARDIS key item.
      usage: /<command> key [material]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    wall:
      description: Set the TARDIS room growing wall material.
      usage: /<command> wall [material]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    floor:
      description: Set the TARDIS room growing floor material.
      usage: /<command> floor [material]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
  tardisarea:
    aliases: tarea
    description: Set up predefined TARDIS travel areas.
    usage: /<command> [start|end|show|remove] [name]
    start:
      description: Start defining a TARDIS area.
      usage: /<command> start [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    end:
      description: Finish defining a TARDIS area.
      usage: /<command> end
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    show:
      description: Show the corners of a TARDIS area.
      usage: /<command> show [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a TARDIS area.
      usage: /<command> remove [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
  tardisbind:
    aliases: tbind
    save:
      description: Bind a saved location to a button.
      usage: /<command> [save name]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    cmd:
      description: Bind the 'home', 'hide' or 'rebuild' commands to a button.
      usage: /<command> [home|hide|rebuild]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    player:
      description: Bind a player location to a button.
      usage: /<command> [player]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    area:
      description: Bind a TARDIS area to a button.
      usage: /<command> [area name]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a 'bound' saved location, command, player or area from a button.
      usage: /<command> [save name|cmd|player|area]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
  tardisgravity:
    aliases: tgravity
    description: Add or remove gravity well blocks.
    usage: /<command> [up|down|north|west|south|east|remove] [distance] [velocity]
    permission: tardis.update
    permission-message: You don't have the permission <permission> to use this command
  tardisbook:
    aliases: tbook
    description: Get and read TARDIS books and start TARDIS achievements.
    usage: /<command> [list|get|start] [book name]
    permission: tardis.book
    permission-message: You don't have the permission <permission> to use this command
